// Emit the SQL migration for every spec in report-specs.ts, so the tables can
// never drift from the parser. Prints to stdout.
//
//   NODE_PATH=/tmp/stub/node_modules npx tsx@4 scripts/gen_report_migration.mts > supabase/migrations/0174_ezyvet_extra_reports.sql
import { REPORT_SPECS, type ColumnType, type ReportSpec } from "@/lib/reporting/report-specs";
import { REPORT_DOCS } from "@/lib/reporting/report-docs";

const SQL_TYPE: Record<ColumnType, string> = {
  text: "text",
  numeric: "numeric",
  int: "bigint",
  bool: "boolean",
  date: "date",
  timestamp: "timestamptz",
  label: "text",
  leading_int: "bigint",
  paren_timestamp: "timestamptz",
  paren_date: "date",
  long_date: "date",
  long_timestamp: "timestamptz",
  dmy_date: "date",
};

function columnsFor(spec: ReportSpec): { name: string; type: string }[] {
  const out: { name: string; type: string }[] = [];
  const seen = new Set<string>();
  const add = (name: string, type: string) => {
    if (seen.has(name)) return;
    seen.add(name);
    out.push({ name, type });
  };
  for (const c of spec.columns) add(c.column, SQL_TYPE[c.type]);
  for (const b of spec.buckets?.columns ?? []) add(b, "numeric");
  if (spec.sectionColumn) add(spec.sectionColumn, "text");
  if (spec.locationFrom || spec.locationFromSection) add("location_key", "text");
  return out;
}

const pad = (s: string, n: number) => s + " ".repeat(Math.max(1, n - s.length));

const parts: string[] = [];
parts.push(`-- ============================================================================
-- Green Dog Ops — 0176 ezyVet extra reports (payments, receivables, close,
-- appointments, clinical, inventory)
-- ----------------------------------------------------------------------------
-- GENERATED by scripts/gen_report_migration.mts from src/lib/reporting/
-- report-specs.ts — regenerate rather than hand-editing, or the parser and the
-- schema will drift apart.
--
-- One table per ezyVet Report Center report pulled by agent/extra-reports.mjs.
-- Every table shares three ingest columns:
--   snapshot_date  the target day of the pull that produced the row
--   period_start   \\
--   period_end     /  the From/To window that was requested
--
-- Reports with a natural key are upserted; the rest are rebuilt for the window
-- they cover, so re-running a day is idempotent either way.
-- ============================================================================
set search_path = greendogops, public;
`);

for (const spec of Object.values(REPORT_SPECS)) {
  const doc = REPORT_DOCS[spec.key];
  const cols = columnsFor(spec);
  const width = Math.max(...cols.map((c) => c.name.length), 14) + 2;

  parts.push(`
-- ---------------------------------------------------------------------------
-- ${doc?.title ?? spec.key} — ezyVet report "${doc?.report ?? spec.key}"
-- ${doc?.purpose ?? ""}
-- ---------------------------------------------------------------------------
create table if not exists greendogops.${spec.table} (
  ${pad("id", width)}uuid primary key default gen_random_uuid(),
${cols.map((c) => `  ${pad(c.name, width)}${c.type},`).join("\n")}

  ${pad("snapshot_date", width)}date not null,
  ${pad("period_start", width)}date,
  ${pad("period_end", width)}date,
  ${pad("created_at", width)}timestamptz not null default now()
);`);

  if (spec.conflict) {
    parts.push(`create unique index if not exists ${spec.table}_key_idx
  on greendogops.${spec.table} (${spec.conflict.join(", ")});`);
  }
  if (spec.dateColumn) {
    parts.push(`create index if not exists ${spec.table}_date_idx
  on greendogops.${spec.table} (${spec.dateColumn});`);
  }
  parts.push(`create index if not exists ${spec.table}_snapshot_idx
  on greendogops.${spec.table} (snapshot_date);`);
  if (spec.locationFrom || spec.locationFromSection) {
    parts.push(`create index if not exists ${spec.table}_location_idx
  on greendogops.${spec.table} (location_key);`);
  }
  if (doc?.comment) {
    parts.push(`comment on table greendogops.${spec.table} is
  '${doc.comment.replace(/'/g, "''")}';`);
  }
}

parts.push(`
-- ---------------------------------------------------------------------------
-- Roll-up views. The Smart Report is told to prefer report_* views so its
-- answers match what the app shows. Snapshot reports expose a "_current" view
-- that pins the latest pull, because querying the raw table without filtering
-- snapshot_date silently multiplies every total by the number of days ingested.
-- ---------------------------------------------------------------------------
create or replace view greendogops.report_daily_collections as
select payment_date,
       location_key,
       coalesce(nullif(payment_method, ''), 'Unknown') as payment_method,
       count(*)          as payment_count,
       sum(amount)       as collected,
       sum(surcharge)    as surcharge
from greendogops.ezyvet_payment
where payment_date is not null
group by 1, 2, 3;

create or replace view greendogops.report_ar_aging_current as
select r.*
from greendogops.ezyvet_aged_receivable r
join (select max(snapshot_date) as d from greendogops.ezyvet_aged_receivable) m
  on r.snapshot_date = m.d;

create or replace view greendogops.report_ar_aging_trend as
select snapshot_date,
       count(*)               as clients_owing,
       sum(total_due)         as total_due,
       sum(bucket_current)    as due_current,
       sum(bucket_30)         as due_30,
       sum(bucket_60)         as due_60,
       sum(bucket_90_plus)    as due_90_plus
from greendogops.ezyvet_aged_receivable
group by 1;

create or replace view greendogops.report_appointment_flow as
select appt_date,
       location_key,
       count(*)                                          as appointments,
       round(avg(mins_in_waiting_room)::numeric, 1)      as avg_wait_minutes,
       round(avg(mins_in_consultation)::numeric, 1)      as avg_consult_minutes,
       round(avg(mins_in_hospital)::numeric, 1)          as avg_hospital_minutes,
       round(avg(mins_to_complete)::numeric, 1)          as avg_minutes_to_complete,
       count(*) filter (where mins_to_complete is null)  as never_completed
from greendogops.ezyvet_appointment_status
where appt_date is not null
group by 1, 2;

create or replace view greendogops.report_unbilled_consults_current as
select c.*
from greendogops.ezyvet_unbilled_consult c
join (select max(snapshot_date) as d from greendogops.ezyvet_unbilled_consult) m
  on c.snapshot_date = m.d;

create or replace view greendogops.report_estimate_conversion as
select date_trunc('month', coalesce(date_sent, period_end))::date as month,
       status,
       count(*)          as estimates,
       sum(total_value)  as total_value
from greendogops.ezyvet_estimate
group by 1, 2;

create or replace view greendogops.report_clinical_note_backlog as
select coalesce(nullif(case_owner, ''), nullif(note_created_by, ''), 'Unassigned') as clinician,
       location_key,
       count(*) filter (where approved_by is null) as unapproved_notes,
       count(*)                                    as total_notes,
       min(note_created_date) filter (where approved_by is null) as oldest_unapproved
from greendogops.ezyvet_clinical_note
group by 1, 2;

create or replace view greendogops.report_soc_overdue_current as
select s.*
from greendogops.ezyvet_soc_overdue s
join (select max(snapshot_date) as d from greendogops.ezyvet_soc_overdue) m
  on s.snapshot_date = m.d;

create or replace view greendogops.report_inventory_on_hand as
select v.*
from greendogops.ezyvet_inventory_value v
join (select max(snapshot_date) as d from greendogops.ezyvet_inventory_value) m
  on v.snapshot_date = m.d;

create or replace view greendogops.report_inventory_value_trend as
select snapshot_date,
       count(*)                     as products,
       sum(total_inventory_value)   as inventory_value
from greendogops.ezyvet_inventory_value
group by 1;

create or replace view greendogops.report_reorder_list as
select o.product_code, o.product_name, o.in_inventory, o.available, o.ordered,
       o.short, o.to_order, o.turn_last_month, o.turn_last_12_months,
       o.avg_monthly_turn, o.snapshot_date
from greendogops.ezyvet_inventory_ordering o
join (select max(snapshot_date) as d from greendogops.ezyvet_inventory_ordering) m
  on o.snapshot_date = m.d
where o.to_order > 0;

create or replace view greendogops.report_wellness_plan_current as
select w.*
from greendogops.ezyvet_wellness_plan_use w
join (select max(snapshot_date) as d from greendogops.ezyvet_wellness_plan_use) m
  on w.snapshot_date = m.d;

grant select on
  greendogops.report_daily_collections,
  greendogops.report_ar_aging_current,
  greendogops.report_ar_aging_trend,
  greendogops.report_appointment_flow,
  greendogops.report_unbilled_consults_current,
  greendogops.report_estimate_conversion,
  greendogops.report_clinical_note_backlog,
  greendogops.report_soc_overdue_current,
  greendogops.report_inventory_on_hand,
  greendogops.report_inventory_value_trend,
  greendogops.report_reorder_list,
  greendogops.report_wellness_plan_current
to service_role;
`);

parts.push(`
-- ---------------------------------------------------------------------------
-- A dedicated agent for the long tail, so a failure here can never jeopardise
-- the core invoice/patient ingest run by ezyvet_daily_ingest.
-- ---------------------------------------------------------------------------
insert into greendogops.agent (key, name, description, schedule_cron, timezone, enabled)
values ('ezyvet_extra_reports', 'ezyVet Extra Reports',
        'Payments, receivables, daily close, appointment timings, clinical compliance and inventory pulled from the ezyVet Report Center.',
        '30 12 * * *', 'America/Los_Angeles', true)
on conflict (key) do nothing;
`);

Object.values(REPORT_SPECS).forEach((spec, i) => {
  const doc = REPORT_DOCS[spec.key];
  const description = (doc?.purpose ?? spec.key).replace(/'/g, "''");
  parts.push(`insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, '${spec.key}', '${(doc?.title ?? spec.key).replace(/'/g, "''")}', 'global',
       '${description}', '${spec.table}', ${i + 1}
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;`);
});

console.log(parts.join("\n"));
