// Emit the SQL migration for every spec in report-specs.ts, so the tables can
// never drift from the parser. Prints to stdout.
//
//   NODE_PATH=/tmp/stub/node_modules npx tsx@4 scripts/gen_report_migration.mts > supabase/migrations/0174_ezyvet_extra_reports.sql
import { REPORT_SPECS, type ColumnType, type ReportSpec } from "@/lib/reporting/report-specs";
import { REPORT_DOCS } from "@/lib/reporting/report-docs";

const SQL_TYPE: Record<ColumnType, string> = {
  text: "text",
  numeric: "numeric",
  int: "bigint",
  bool: "boolean",
  date: "date",
  timestamp: "timestamptz",
  label: "text",
  leading_int: "bigint",
  paren_timestamp: "timestamptz",
  paren_date: "date",
  long_date: "date",
  long_timestamp: "timestamptz",
};

function columnsFor(spec: ReportSpec): { name: string; type: string }[] {
  const out: { name: string; type: string }[] = [];
  const seen = new Set<string>();
  const add = (name: string, type: string) => {
    if (seen.has(name)) return;
    seen.add(name);
    out.push({ name, type });
  };
  for (const c of spec.columns) add(c.column, SQL_TYPE[c.type]);
  for (const b of spec.buckets?.columns ?? []) add(b, "numeric");
  if (spec.sectionColumn) add(spec.sectionColumn, "text");
  if (spec.locationFrom || spec.locationFromSection) add("location_key", "text");
  return out;
}

const pad = (s: string, n: number) => s + " ".repeat(Math.max(1, n - s.length));

const parts: string[] = [];
parts.push(`-- ============================================================================
-- Green Dog Ops — 0174 ezyVet extra reports (payments, receivables, close,
-- appointments, clinical, inventory)
-- ----------------------------------------------------------------------------
-- GENERATED by scripts/gen_report_migration.mts from src/lib/reporting/
-- report-specs.ts — regenerate rather than hand-editing, or the parser and the
-- schema will drift apart.
--
-- One table per ezyVet Report Center report pulled by agent/extra-reports.mjs.
-- Every table shares three ingest columns:
--   snapshot_date  the target day of the pull that produced the row
--   period_start   \\
--   period_end     /  the From/To window that was requested
--
-- Reports with a natural key are upserted; the rest are rebuilt for the window
-- they cover, so re-running a day is idempotent either way.
-- ============================================================================
set search_path = greendogops, public;
`);

for (const spec of Object.values(REPORT_SPECS)) {
  const doc = REPORT_DOCS[spec.key];
  const cols = columnsFor(spec);
  const width = Math.max(...cols.map((c) => c.name.length), 14) + 2;

  parts.push(`
-- ---------------------------------------------------------------------------
-- ${doc?.title ?? spec.key} — ezyVet report "${doc?.report ?? spec.key}"
-- ${doc?.purpose ?? ""}
-- ---------------------------------------------------------------------------
create table if not exists greendogops.${spec.table} (
  ${pad("id", width)}uuid primary key default gen_random_uuid(),
${cols.map((c) => `  ${pad(c.name, width)}${c.type},`).join("\n")}

  ${pad("snapshot_date", width)}date not null,
  ${pad("period_start", width)}date,
  ${pad("period_end", width)}date,
  ${pad("created_at", width)}timestamptz not null default now()
);`);

  if (spec.conflict) {
    parts.push(`create unique index if not exists ${spec.table}_key_idx
  on greendogops.${spec.table} (${spec.conflict.join(", ")});`);
  }
  if (spec.dateColumn) {
    parts.push(`create index if not exists ${spec.table}_date_idx
  on greendogops.${spec.table} (${spec.dateColumn});`);
  }
  parts.push(`create index if not exists ${spec.table}_snapshot_idx
  on greendogops.${spec.table} (snapshot_date);`);
  if (spec.locationFrom || spec.locationFromSection) {
    parts.push(`create index if not exists ${spec.table}_location_idx
  on greendogops.${spec.table} (location_key);`);
  }
  if (doc?.comment) {
    parts.push(`comment on table greendogops.${spec.table} is
  '${doc.comment.replace(/'/g, "''")}';`);
  }
}

parts.push(`
-- ---------------------------------------------------------------------------
-- A dedicated agent for the long tail, so a failure here can never jeopardise
-- the core invoice/patient ingest run by ezyvet_daily_ingest.
-- ---------------------------------------------------------------------------
insert into greendogops.agent (key, name, description, schedule_cron, timezone, is_enabled)
values ('ezyvet_extra_reports', 'ezyVet Extra Reports',
        'Payments, receivables, daily close, appointment timings, clinical compliance and inventory pulled from the ezyVet Report Center.',
        '30 12 * * *', 'America/Los_Angeles', true)
on conflict (key) do nothing;
`);

Object.values(REPORT_SPECS).forEach((spec, i) => {
  const doc = REPORT_DOCS[spec.key];
  const description = (doc?.purpose ?? spec.key).replace(/'/g, "''");
  parts.push(`insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, '${spec.key}', '${(doc?.title ?? spec.key).replace(/'/g, "''")}', 'global',
       '${description}', '${spec.table}', ${i + 1}
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;`);
});

console.log(parts.join("\n"));
