#!/usr/bin/env node
/**
 * Generate idempotent SQL that loads the DVM placements from the GDD Staff
 * Schedule sheet into sched_assignment.
 *
 *   node scripts/read_schedule_sheet.mjs extract September vet
 *   node scripts/match_sheet_names.mjs .data/sheet_September_vet.json
 *   node scripts/import_sheet_dvm.mjs > .data/import_dvm.sql
 *
 * Scope is deliberately narrow: only the nine VET-* rows, which map 1:1 onto a
 * (department, DVM) scheduling line, so no section inheritance guessing is
 * needed. Weeks already published in the app are skipped so a hand-built week
 * is never overwritten.
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const placements = JSON.parse(
  fs.readFileSync(path.join(ROOT, ".data/sheet_September_vet.json"), "utf8"),
);
const nameMap = JSON.parse(fs.readFileSync(path.join(ROOT, ".data/name_map.json"), "utf8"));

/** Sheet role row -> scheduling department; `second` picks the 2nd DVM line. */
const ROLE_TO_DEPT = {
  "VET-SURGERY": { dept: "SURGERY", second: false },
  "VET-AP": { dept: "AP", second: false },
  "2nd VET-AP": { dept: "AP", second: true },
  "VET-NAD": { dept: "NAD/VE/UC", second: false },
  "2nd VET-NAD": { dept: "NAD/VE/UC", second: true },
  "VET-IM": { dept: "IM", second: false },
  "VET-EXOTICS": { dept: "EXOTICS", second: false },
  "VET-MPMV": { dept: "MPMV", second: false },
  "VET-CARDIO": { dept: "CARDIO", second: false },
};

const SHEET_LOCATIONS = { SO: "Sherman Oaks", VENICE: "Venice", AETNA: "Van Nuys" };

/** Sunday that starts the sched_week containing `date`. */
function weekStart(dateStr) {
  const d = new Date(`${dateStr}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() - d.getUTCDay());
  return d.toISOString().slice(0, 10);
}

const rows = [];
const skipped = { name: 0, role: 0 };
for (const p of placements) {
  const map = ROLE_TO_DEPT[p.role];
  if (!map) {
    skipped.role++;
    continue;
  }
  const person = nameMap[p.person];
  if (!person) {
    skipped.name++;
    continue;
  }
  rows.push({
    week_start: weekStart(p.date),
    work_date: p.date,
    dow: new Date(`${p.date}T00:00:00Z`).getUTCDay(),
    dept: map.dept,
    second: map.second,
    location: SHEET_LOCATIONS[p.location],
    person_id: person.id,
    person_name: person.full_name,
    pub: p.pub,
  });
}

const weeks = [...new Set(rows.map((r) => r.week_start))].sort();
const esc = (s) => String(s).replace(/'/g, "''");

console.log(`-- Generated by scripts/import_sheet_dvm.mjs on ${new Date().toISOString()}`);
console.log(`-- ${rows.length} DVM placements across ${weeks.length} weeks: ${weeks.join(", ")}`);
console.log(`-- skipped: ${skipped.name} unmatched name(s), ${skipped.role} non-DVM row(s)`);
console.log(`--
-- Idempotent: clears DVM-line assignments for each target week, then reinserts.
-- Weeks whose status is already 'published' are left untouched.
`);
console.log("begin;\n");

for (const ws of weeks) {
  const wr = rows.filter((r) => r.week_start === ws);
  console.log(`-- ================ week of ${ws} (${wr.length} placements) ================`);
  console.log(`do $$
declare
  v_week uuid;
begin
  select id into v_week from greendogops.sched_week
   where week_start = '${ws}' and coalesce(is_template,false) = false
     and status <> 'published'
   limit 1;
  if v_week is null then
    raise notice 'week ${ws}: missing or already published — skipped';
    return;
  end if;

  delete from greendogops.sched_assignment a
   using greendogops.sched_week_line l, greendogops.sched_role r
   where a.week_id = v_week and l.id = a.line_id
     and r.id = l.role_id and r.name = 'DVM';
`);

  for (const r of wr) {
    // "2nd VET-*" wants the department's second DVM line, but NAD/VE/UC only
    // has one. least(pick, cnt) falls back to the single line rather than
    // silently dropping the placement (there is no unique constraint on
    // line/location/day, and two DVMs a day already occur in published weeks).
    const pick = r.second ? 2 : 1;
    console.log(`  insert into greendogops.sched_assignment
    (week_id, line_id, location_id, person_id, day_of_week, work_date)
  select v_week, ln.id, loc.id, '${r.person_id}'::uuid, ${r.dow}, '${r.work_date}'::date
    from (
      select l.id,
             row_number() over (order by l.sort_order) rn,
             count(*) over () cnt
        from greendogops.sched_week_line l
        join greendogops.sched_department d on d.id = l.department_id and d.name = '${esc(r.dept)}'
        join greendogops.sched_role rr on rr.id = l.role_id and rr.name = 'DVM'
       where l.week_id = v_week
    ) ln
    cross join lateral (
      select id from greendogops.location where name = '${esc(r.location)}' limit 1
    ) loc
   where ln.rn = least(${pick}, ln.cnt)
   limit 1;   -- ${r.person_name} @ ${r.location} ${r.work_date}`);
  }

  console.log(`end $$;\n`);
}

console.log("commit;");
console.error(
  `generated ${rows.length} inserts across ${weeks.length} weeks (skipped ${skipped.name} unmatched names)`,
);
