#!/usr/bin/env node
/**
 * Full-text index the PDFs uploaded to the Resources library so Smart Report
 * can answer questions about what they SAY.
 *
 *   node scripts/ingest_resource_pdfs.mjs --apply
 *   node scripts/ingest_resource_pdfs.mjs > out.sql   # review first
 *
 * Only Google Docs were ever indexed (ingest_google_docs.mjs); documents that
 * live as an uploaded file in the `resources` storage bucket had no text at
 * all, so operations/safety/training PDFs were invisible to Smart Report.
 *
 * By default only documents with NO chunks are processed. --all re-extracts
 * every PDF (use after replacing a file).
 *
 * Without --apply this emits idempotent SQL, like the other importers. The
 * extracted text runs to ~600KB though, which is past what the Supabase SQL
 * API accepts in one request, so --apply writes the chunks through the
 * service-role client instead.
 */
import { createClient } from "@supabase/supabase-js";
import { env } from "./lib/google-auth.mjs";
import { chunkText, dollarQuote, sqlString as q } from "./lib/chunk-text.mjs";

const ALL = process.argv.includes("--all");
const APPLY = process.argv.includes("--apply");
const BUCKET = "resources";
/** Below this, the PDF is a scan with no text layer — flag it, don't index noise. */
const MIN_TEXT_CHARS = 200;

const url = env("NEXT_PUBLIC_SUPABASE_URL");
const key = env("SUPABASE_SERVICE_ROLE_KEY");
if (!url || !key) {
  console.error("NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required.");
  process.exit(1);
}
const supabase = createClient(url, key, {
  auth: { persistSession: false },
  db: { schema: "greendogops" },
});

async function extractPdfText(buffer) {
  const { getDocumentProxy, extractText } = await import("unpdf");
  const pdf = await getDocumentProxy(new Uint8Array(buffer));
  const { text } = await extractText(pdf, { mergePages: true });
  return (Array.isArray(text) ? text.join("\n") : text)
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

const { data: docs, error } = await supabase
  .from("resource_document")
  .select("id, title, storage_path, mime_type, is_active")
  .not("storage_path", "is", null)
  .order("title");
if (error) {
  console.error(`Could not list documents: ${error.message}`);
  process.exit(1);
}

const { data: indexed } = await supabase
  .from("resource_document_chunk")
  .select("document_id");
const hasChunks = new Set((indexed ?? []).map((r) => r.document_id));

const todo = docs.filter((d) => ALL || !hasChunks.has(d.id));
console.error(`${docs.length} stored files, ${todo.length} to index${ALL ? " (--all)" : ""}`);

const out = [
  "-- Generated by scripts/ingest_resource_pdfs.mjs — do not edit by hand.",
  "set search_path = greendogops, public;",
  "begin;",
];
const skipped = [];

for (const doc of todo) {
  const { data: file, error: dlError } = await supabase.storage
    .from(BUCKET)
    .download(doc.storage_path);
  if (dlError || !file) {
    skipped.push(`${doc.title}: download failed (${dlError?.message ?? "no file"})`);
    continue;
  }

  let text;
  try {
    text = await extractPdfText(Buffer.from(await file.arrayBuffer()));
  } catch (err) {
    skipped.push(`${doc.title}: ${err.message}`);
    continue;
  }
  if (text.length < MIN_TEXT_CHARS) {
    skipped.push(`${doc.title}: only ${text.length} chars — image-only scan?`);
    continue;
  }

  const chunks = chunkText(text);
  console.error(`  ${doc.title} — ${text.length} chars, ${chunks.length} chunks`);

  if (APPLY) {
    await supabase.from("resource_document_chunk").delete().eq("document_id", doc.id);
    const { error: insError } = await supabase.from("resource_document_chunk").insert(
      chunks.map((content, chunk_index) => ({ document_id: doc.id, chunk_index, content })),
    );
    if (insError) {
      skipped.push(`${doc.title}: insert failed (${insError.message})`);
      continue;
    }
    await supabase
      .from("resource_document")
      .update({ content_synced_at: new Date().toISOString() })
      .eq("id", doc.id);
    continue;
  }

  out.push("", `-- ${doc.title}`);
  out.push(`delete from greendogops.resource_document_chunk where document_id = ${q(doc.id)}::uuid;`);
  chunks.forEach((c, i) => {
    out.push(`insert into greendogops.resource_document_chunk (document_id, chunk_index, content)
values (${q(doc.id)}::uuid, ${i}, ${dollarQuote(c)});`);
  });
  out.push(`update greendogops.resource_document
   set content_synced_at = now() where id = ${q(doc.id)}::uuid;`);
}

out.push("", "commit;");
if (!APPLY) console.log(out.join("\n"));

if (skipped.length) {
  console.error(`\nSKIPPED ${skipped.length}:`);
  for (const s of skipped) console.error(`  ${s}`);
}
