#!/usr/bin/env node
/**
 * Ingest a Google Doc "index" page (one whose links point at the real content)
 * into the Resources library, and full-text index every linked document so
 * Smart Report can answer questions about what they SAY.
 *
 *   node scripts/ingest_google_docs.mjs <index-doc-url> [--category hr] > out.sql
 *   ./scripts/supabase-sql.sh -f out.sql
 *
 * Emits idempotent SQL only — nothing is written to Supabase from here, matching
 * the other importers. Re-running refreshes the text of documents that changed.
 *
 * Each linked document becomes a link-only resource_document row keyed by
 * google_file_id, plus resource_document_chunk rows (migration 0174).
 */
import { parseFileId } from "./lib/google-auth.mjs";
import { fetchFileText } from "./lib/google-docs.mjs";

const target = process.argv[2];
if (!target) {
  console.error(
    "usage: node scripts/ingest_google_docs.mjs <index-doc-url> [--category hr]",
  );
  process.exit(1);
}
const catArg = process.argv.indexOf("--category");
const CATEGORY = catArg !== -1 ? process.argv[catArg + 1] : "hr";
const CHUNK_CHARS = 1500;
const CHUNK_OVERLAP = 200;

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
/** Dollar-quote document text so apostrophes and newlines survive untouched. */
function dollar(s) {
  let tag = "$doc$";
  for (let i = 1; s.includes(tag); i++) tag = `$doc${i}$`;
  return `${tag}${s}${tag}`;
}

/** Break text into pieces no larger than CHUNK_CHARS, preferring paragraph then
 *  line boundaries. .docx text has no blank lines, so splitting only on those
 *  leaves whole documents in a single piece. */
const SEPARATORS = [/\n\s*\n/, /\n/];

function splitToSize(text, level = 0) {
  const pieces = [];
  const parts = level < SEPARATORS.length ? text.split(SEPARATORS[level]) : [text];
  for (const part of parts) {
    const t = part.trim();
    if (!t) continue;
    if (t.length <= CHUNK_CHARS) {
      pieces.push(t);
    } else if (level < SEPARATORS.length) {
      pieces.push(...splitToSize(t, level + 1));
    } else {
      for (let i = 0; i < t.length; i += CHUNK_CHARS) {
        pieces.push(t.slice(i, i + CHUNK_CHARS));
      }
    }
  }
  return pieces;
}

/** Pack paragraphs up to CHUNK_CHARS, carrying a little overlap for context. */
function chunkText(text) {
  const chunks = [];
  let buf = "";
  for (const p of splitToSize(text)) {
    if (buf && buf.length + p.length + 2 > CHUNK_CHARS) {
      chunks.push(buf);
      buf = buf.slice(-CHUNK_OVERLAP);
    }
    buf = buf ? `${buf}\n\n${p}` : p;
  }
  if (buf.trim()) chunks.push(buf);
  return chunks;
}

const indexId = parseFileId(target);
const index = await fetchFileText(indexId);
console.error(`index: ${index.meta.name} — ${index.links.length} links`);

// The index doc itself is worth storing too; dedupe links that repeat.
const seen = new Set();
const targets = [{ id: indexId, label: index.meta.name, known: index }];
for (const link of index.links) {
  const id = parseFileId(link.url);
  if (!/^[a-zA-Z0-9_-]{20,}$/.test(id) || id === indexId || seen.has(id)) continue;
  seen.add(id);
  targets.push({ id, label: link.label });
}

const out = [];
out.push("-- Generated by scripts/ingest_google_docs.mjs — do not edit by hand.");
out.push("set search_path = greendogops, public;");
out.push("begin;");

const skipped = [];
for (const t of targets) {
  let doc;
  try {
    doc = t.known ?? (await fetchFileText(t.id));
  } catch (err) {
    skipped.push(`${t.label || t.id}: ${err.noAccess ? "no access" : err.message}`);
    continue;
  }
  const title = doc.meta.name.replace(/\.docx$/i, "").trim();
  const url = doc.meta.webViewLink ?? `https://docs.google.com/document/d/${t.id}/edit`;
  const chunks = chunkText(doc.text);
  if (!chunks.length) {
    skipped.push(`${title}: no text extracted`);
    continue;
  }
  console.error(`  ${title} — ${doc.text.length} chars, ${chunks.length} chunks (${doc.mode})`);

  out.push("");
  out.push(`-- ${title}`);
  out.push(`insert into greendogops.resource_document
  (title, category, description, source_url, google_file_id, staff_only, sort_order)
values (${q(title)}, ${q(CATEGORY)}, ${q(t.label && t.label !== title ? t.label : "")},
        ${q(url)}, ${q(t.id)}, true, 50)
on conflict (google_file_id) where google_file_id is not null
do update set title = excluded.title,
              source_url = excluded.source_url,
              updated_at = now();`);
  out.push(`delete from greendogops.resource_document_chunk
 where document_id = (select id from greendogops.resource_document
                       where google_file_id = ${q(t.id)});`);
  chunks.forEach((c, i) => {
    out.push(`insert into greendogops.resource_document_chunk (document_id, chunk_index, content)
select id, ${i}, ${dollar(c)}
  from greendogops.resource_document where google_file_id = ${q(t.id)};`);
  });
  out.push(`update greendogops.resource_document
   set content_synced_at = now() where google_file_id = ${q(t.id)};`);
}

out.push("");
out.push("commit;");
console.log(out.join("\n"));

if (skipped.length) {
  console.error(`\nSKIPPED ${skipped.length}:`);
  for (const s of skipped) console.error(`  ${s}`);
}
