-- 0081_seed_policy_documents.sql
-- Seed policy PDFs uploaded to the private `resources` bucket into the
-- resources library. Files were uploaded via scripts/upload_policies.py.
-- Idempotent: each insert is guarded on storage_path so re-running is safe.

insert into greendogops.resource_document (title, category, description, storage_path, file_name, mime_type, size_bytes, staff_only, sort_order) select 'Employee Pet Policy', 'hr', 'Policy covering employees bringing pets to the workplace.', 'employee-pet-policy.pdf', 'Employee Pet Policy.pdf', 'application/pdf', 331734, false, 20 where not exists (select 1 from greendogops.resource_document where storage_path = 'employee-pet-policy.pdf');
insert into greendogops.resource_document (title, category, description, storage_path, file_name, mime_type, size_bytes, staff_only, sort_order) select 'Compensation Overview', 'hr', 'Overview of the company compensation structure.', 'gdd-compensation-overview.pdf', 'GDD COMPENSATION OVERVIEW.pdf', 'application/pdf', 65821, false, 15 where not exists (select 1 from greendogops.resource_document where storage_path = 'gdd-compensation-overview.pdf');
insert into greendogops.resource_document (title, category, description, storage_path, file_name, mime_type, size_bytes, staff_only, sort_order) select 'Core Attributes', 'hr', 'The core attributes expected of Green Dog team members.', 'gdd-core-attributes.pdf', 'GDD CORE ATTRIBUTES.pdf', 'application/pdf', 74916, false, 12 where not exists (select 1 from greendogops.resource_document where storage_path = 'gdd-core-attributes.pdf');
insert into greendogops.resource_document (title, category, description, storage_path, file_name, mime_type, size_bytes, staff_only, sort_order) select 'Harassment Policy', 'hr', 'Company anti-harassment policy.', 'gdd-harassment-policy.pdf', 'GDD Harassment Policy.pdf', 'application/pdf', 105150, false, 30 where not exists (select 1 from greendogops.resource_document where storage_path = 'gdd-harassment-policy.pdf');
insert into greendogops.resource_document (title, category, description, storage_path, file_name, mime_type, size_bytes, staff_only, sort_order) select 'PTO / Sick Time / Unpaid Time Off Policy', 'hr', 'Paid time off, sick time, and unpaid time off policy.', 'gdd-pto-sick-time-unpaid-time-off-policy.pdf', 'GDD PTO_Sick Time_Unpaid Time Off Policy.pdf', 'application/pdf', 144936, false, 25 where not exists (select 1 from greendogops.resource_document where storage_path = 'gdd-pto-sick-time-unpaid-time-off-policy.pdf');
insert into greendogops.resource_document (title, category, description, storage_path, file_name, mime_type, size_bytes, staff_only, sort_order) select 'Pregnancy Safety', 'safety', 'Workplace safety guidance for pregnant employees.', 'gdd-pregnancy-safety-docx.pdf', 'GDD Pregnancy Safety.docx.pdf', 'application/pdf', 84180, false, 20 where not exists (select 1 from greendogops.resource_document where storage_path = 'gdd-pregnancy-safety-docx.pdf');
insert into greendogops.resource_document (title, category, description, storage_path, file_name, mime_type, size_bytes, staff_only, sort_order) select 'Respectful Workplace Policy', 'hr', 'Policy establishing standards for a respectful workplace.', 'gdd-respectful-workplace-policy-docx.pdf', 'GDD Respectful Workplace Policy.docx.pdf', 'application/pdf', 105187, false, 31 where not exists (select 1 from greendogops.resource_document where storage_path = 'gdd-respectful-workplace-policy-docx.pdf');
insert into greendogops.resource_document (title, category, description, storage_path, file_name, mime_type, size_bytes, staff_only, sort_order) select 'Review Process', 'hr', 'Employee performance review process.', 'gdd-review-process.pdf', 'GDD Review Process.pdf', 'application/pdf', 443196, false, 18 where not exists (select 1 from greendogops.resource_document where storage_path = 'gdd-review-process.pdf');
insert into greendogops.resource_document (title, category, description, storage_path, file_name, mime_type, size_bytes, staff_only, sort_order) select 'Roles & Responsibilities', 'hr', 'Roles and responsibilities across the practice.', 'gdd-roles.pdf', 'GDD Roles .pdf', 'application/pdf', 1116225, false, 11 where not exists (select 1 from greendogops.resource_document where storage_path = 'gdd-roles.pdf');
insert into greendogops.resource_document (title, category, description, storage_path, file_name, mime_type, size_bytes, staff_only, sort_order) select 'Rescue Partners — General Agreement', 'operations', 'General agreement governing rescue-partner relationships.', 'gddvc-general-rescue-partners-agreement.pdf', 'GDDVC - General Rescue Partners Agreement.pdf', 'application/pdf', 261078, false, 40 where not exists (select 1 from greendogops.resource_document where storage_path = 'gddvc-general-rescue-partners-agreement.pdf');
insert into greendogops.resource_document (title, category, description, storage_path, file_name, mime_type, size_bytes, staff_only, sort_order) select 'Rescue Partners — Protocols & Guidelines', 'operations', 'Protocols and guidelines for working with rescue partners.', 'gddvc-rescue-partners-protocols-guidelines.pdf', 'GDDVC - Rescue Partners Protocols & Guidelines.pdf', 'application/pdf', 561372, false, 41 where not exists (select 1 from greendogops.resource_document where storage_path = 'gddvc-rescue-partners-protocols-guidelines.pdf');
insert into greendogops.resource_document (title, category, description, storage_path, file_name, mime_type, size_bytes, staff_only, sort_order) select 'Rescue Partners — Rescue Vetting', 'operations', 'Vetting process and requirements for rescue partners.', 'gddvc-rescue-partners-all-rescue-vetting.pdf', 'GDDVC Rescue Partners  - ALL RESCUE VETTING.pdf', 'application/pdf', 107121, false, 42 where not exists (select 1 from greendogops.resource_document where storage_path = 'gddvc-rescue-partners-all-rescue-vetting.pdf');
insert into greendogops.resource_document (title, category, description, storage_path, file_name, mime_type, size_bytes, staff_only, sort_order) select 'Continuing Education Policy', 'hr', 'Continuing education policy and allowances.', 'gdd-continuing-education-policy.pdf', 'Gdd Continuing Education policy.pdf', 'application/pdf', 159035, false, 32 where not exists (select 1 from greendogops.resource_document where storage_path = 'gdd-continuing-education-policy.pdf');
insert into greendogops.resource_document (title, category, description, storage_path, file_name, mime_type, size_bytes, staff_only, sort_order) select 'Attendance Policy', 'hr', 'Attendance, call-out, and tardiness policy.', 'green-dog-attendance-policy-docx.pdf', 'Green Dog Attendance Policy.docx.pdf', 'application/pdf', 268896, false, 33 where not exists (select 1 from greendogops.resource_document where storage_path = 'green-dog-attendance-policy-docx.pdf');
insert into greendogops.resource_document (title, category, description, storage_path, file_name, mime_type, size_bytes, staff_only, sort_order) select 'Safety & Best Practice Handbook', 'safety', 'Company safety manual and best-practice handbook.', 'green-dog-safety-and-best-practice-handbook-docx.pdf', 'Green Dog Safety and Best Practice Handbook.docx.pdf', 'application/pdf', 763055, false, 10 where not exists (select 1 from greendogops.resource_document where storage_path = 'green-dog-safety-and-best-practice-handbook-docx.pdf');
insert into greendogops.resource_document (title, category, description, storage_path, file_name, mime_type, size_bytes, staff_only, sort_order) select 'Non-Employee Pet Discounts', 'hr', 'Pet-care discount policy for non-employees.', 'non-employee-pet-discounts.pdf', 'Non-Employee Pet Discounts.pdf', 'application/pdf', 113822, false, 34 where not exists (select 1 from greendogops.resource_document where storage_path = 'non-employee-pet-discounts.pdf');
insert into greendogops.resource_document (title, category, description, storage_path, file_name, mime_type, size_bytes, staff_only, sort_order) select 'Safety Hazard Report Form', 'forms', 'Form for reporting workplace safety hazards.', 'safety-hazard-report-form-docx.pdf', 'Safety Hazard Report Form.docx.pdf', 'application/pdf', 61505, false, 20 where not exists (select 1 from greendogops.resource_document where storage_path = 'safety-hazard-report-form-docx.pdf');
insert into greendogops.resource_document (title, category, description, storage_path, file_name, mime_type, size_bytes, staff_only, sort_order) select 'Workplace Relationships Policy', 'hr', 'Policy governing personal relationships between employees.', 'workplace-relationships-policy.pdf', 'Workplace Relationships Policy.pdf', 'application/pdf', 93744, false, 35 where not exists (select 1 from greendogops.resource_document where storage_path = 'workplace-relationships-policy.pdf');
