-- ============================================================================
-- Green Dog Ops — 0176 ezyVet extra reports (payments, receivables, close,
-- appointments, clinical, inventory)
-- ----------------------------------------------------------------------------
-- GENERATED by scripts/gen_report_migration.mts from src/lib/reporting/
-- report-specs.ts — regenerate rather than hand-editing, or the parser and the
-- schema will drift apart.
--
-- One table per ezyVet Report Center report pulled by agent/extra-reports.mjs.
-- Every table shares three ingest columns:
--   snapshot_date  the target day of the pull that produced the row
--   period_start   \
--   period_end     /  the From/To window that was requested
--
-- Reports with a natural key are upserted; the rest are rebuilt for the window
-- they cover, so re-running a day is idempotent either way.
-- ============================================================================
set search_path = greendogops, public;


-- ---------------------------------------------------------------------------
-- Payments — ezyVet report "Payment Summary"
-- Every payment taken, by method and hospital — what was actually COLLECTED.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_payment (
  id                    uuid primary key default gen_random_uuid(),
  payment_date          date,
  paid_at               timestamptz,
  payment_number        bigint,
  division              text,
  customer_code         text,
  customer              text,
  amount                numeric,
  surcharge             numeric,
  card_brand            text,
  integrated_surcharge  numeric,
  created_by            text,
  modified_by           text,
  payment_method        text,
  location_key          text,

  snapshot_date         date not null,
  period_start          date,
  period_end            date,
  created_at            timestamptz not null default now()
);
create index if not exists ezyvet_payment_date_idx
  on greendogops.ezyvet_payment (payment_date);
create index if not exists ezyvet_payment_snapshot_idx
  on greendogops.ezyvet_payment (snapshot_date);
create index if not exists ezyvet_payment_location_idx
  on greendogops.ezyvet_payment (location_key);
comment on table greendogops.ezyvet_payment is
  'One row per payment received, from the ezyVet Payment Summary report. payment_method is the section the payment was listed under (Visa, Cash, CareCredit, Remote Payment...), card_brand the specific card. This is CASH COLLECTED and is NOT the same as revenue billed (ezyvet_invoice_line): a payment may settle an older invoice, and an invoice may go unpaid. Use this for deposits, payment-mix and collections questions.';

-- ---------------------------------------------------------------------------
-- Payment Allocations — ezyVet report "Payment Allocations To Divisions"
-- How each payment was split across hospitals/divisions.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_payment_allocation (
  id                    uuid primary key default gen_random_uuid(),
  allocation_date       date,
  payment_number        bigint,
  payment_division      text,
  client                text,
  invoice_number        bigint,
  division              text,
  divisional_amount     numeric,
  total_for_invoice     numeric,
  total_payment_amount  numeric,
  location_key          text,

  snapshot_date         date not null,
  period_start          date,
  period_end            date,
  created_at            timestamptz not null default now()
);
create index if not exists ezyvet_payment_allocation_date_idx
  on greendogops.ezyvet_payment_allocation (allocation_date);
create index if not exists ezyvet_payment_allocation_snapshot_idx
  on greendogops.ezyvet_payment_allocation (snapshot_date);
create index if not exists ezyvet_payment_allocation_location_idx
  on greendogops.ezyvet_payment_allocation (location_key);
comment on table greendogops.ezyvet_payment_allocation is
  'One row per payment-to-invoice allocation. Shows which division earned the money when a payment taken at one hospital settles another''s invoice. divisional_amount is that division''s share; total_payment_amount repeats the whole payment, so NEVER sum total_payment_amount across rows.';

-- ---------------------------------------------------------------------------
-- Aged Receivables — ezyVet report "Aged Receivables"
-- Client accounts receivable, aged into 30/60/90+ day buckets.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_aged_receivable (
  id                     uuid primary key default gen_random_uuid(),
  contact_code           text,
  title                  text,
  client                 text,
  first_name             text,
  contact_tags           text,
  email                  text,
  total_due              numeric,
  last_30_days_payments  numeric,
  bucket_current         numeric,
  bucket_30              numeric,
  bucket_60              numeric,
  bucket_90_plus         numeric,

  snapshot_date          date not null,
  period_start           date,
  period_end             date,
  created_at             timestamptz not null default now()
);
create unique index if not exists ezyvet_aged_receivable_key_idx
  on greendogops.ezyvet_aged_receivable (contact_code, snapshot_date);
create index if not exists ezyvet_aged_receivable_snapshot_idx
  on greendogops.ezyvet_aged_receivable (snapshot_date);
comment on table greendogops.ezyvet_aged_receivable is
  'Daily snapshot of client A/R (one row per client per snapshot_date, so the aging can be trended). ezyVet names the aging columns after calendar months, which move every month, so they are stored positionally: bucket_current is the newest month, then bucket_30 / bucket_60 / bucket_90_plus going further back. total_due is the balance owed. Join to ezyvet_contact on contact_code.';

-- ---------------------------------------------------------------------------
-- End of Day Totals — ezyVet report "End of Day Totals"
-- Daily close: pending vs approved invoices, payments by type, debtor balances.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_end_of_day (
  id              uuid primary key default gen_random_uuid(),
  metric          text,
  amount          numeric,

  snapshot_date   date not null,
  period_start    date,
  period_end      date,
  created_at      timestamptz not null default now()
);
create unique index if not exists ezyvet_end_of_day_key_idx
  on greendogops.ezyvet_end_of_day (metric, snapshot_date);
create index if not exists ezyvet_end_of_day_snapshot_idx
  on greendogops.ezyvet_end_of_day (snapshot_date);
comment on table greendogops.ezyvet_end_of_day is
  'Long-form daily close figures — one row per metric per day. Metrics include Pending Invoices, Approved Invoices, Opening Debtors, Closing Debtors, Payments Received, plus one row per payment method. Query with metric ILIKE, and remember amounts are practice-wide for that day.';

-- ---------------------------------------------------------------------------
-- Invoices & Credits — ezyVet report "Invoice/Credit Summary"
-- Invoice-header level view: status, credits, amount due, pet and insurance.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_invoice_summary (
  id                      uuid primary key default gen_random_uuid(),
  contact_code            text,
  invoice_date            date,
  invoice_number          bigint,
  purchase_order          text,
  client                  text,
  status                  text,
  total_credits_incl      numeric,
  total_debits_incl       numeric,
  amount_excl             numeric,
  amount_incl             numeric,
  amount_due              numeric,
  due_at                  timestamptz,
  contact_department      text,
  pet_code                text,
  pet_name                text,
  pet_insurance_supplier  text,
  pet_insurance_number    text,
  invoice_department      text,
  invoice_comments        text,
  payment_terms           text,
  location_key            text,

  snapshot_date           date not null,
  period_start            date,
  period_end              date,
  created_at              timestamptz not null default now()
);
create unique index if not exists ezyvet_invoice_summary_key_idx
  on greendogops.ezyvet_invoice_summary (invoice_number);
create index if not exists ezyvet_invoice_summary_date_idx
  on greendogops.ezyvet_invoice_summary (invoice_date);
create index if not exists ezyvet_invoice_summary_snapshot_idx
  on greendogops.ezyvet_invoice_summary (snapshot_date);
create index if not exists ezyvet_invoice_summary_location_idx
  on greendogops.ezyvet_invoice_summary (location_key);
comment on table greendogops.ezyvet_invoice_summary is
  'One row per INVOICE (ezyvet_invoice_line holds the line detail, this holds the header). Adds what lines cannot answer: status (Approved/Pending), credits vs debits, amount still due, due date, and the pet the invoice was for. Re-read on a rolling window and upserted, because invoices flip from Pending to Approved days later.';

-- ---------------------------------------------------------------------------
-- Unapplied Payments & Credits — ezyVet report "Unapplied Payments and Credits"
-- Client money received but not yet allocated to an invoice.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_unapplied_payment (
  id              uuid primary key default gen_random_uuid(),
  payment_number  bigint,
  payment_date    date,
  client_code     text,
  client_name     text,
  record_type     text,
  amount          numeric,

  snapshot_date   date not null,
  period_start    date,
  period_end      date,
  created_at      timestamptz not null default now()
);
create index if not exists ezyvet_unapplied_payment_date_idx
  on greendogops.ezyvet_unapplied_payment (payment_date);
create index if not exists ezyvet_unapplied_payment_snapshot_idx
  on greendogops.ezyvet_unapplied_payment (snapshot_date);
comment on table greendogops.ezyvet_unapplied_payment is
  'Payments and credits sitting unapplied on client accounts. Amounts are negative (money held). A row disappearing means it was applied, so this is a worklist, not a ledger.';

-- ---------------------------------------------------------------------------
-- Taxable Sales — ezyVet report "Taxable Sales"
-- Invoiced totals and tax collected per tax code, per department.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_taxable_sales (
  id                   uuid primary key default gen_random_uuid(),
  tax_code             text,
  tax_percent          numeric,
  total_invoiced_excl  numeric,
  total_tax            numeric,
  total_invoiced_incl  numeric,
  department           text,
  location_key         text,

  snapshot_date        date not null,
  period_start         date,
  period_end           date,
  created_at           timestamptz not null default now()
);
create index if not exists ezyvet_taxable_sales_snapshot_idx
  on greendogops.ezyvet_taxable_sales (snapshot_date);
create index if not exists ezyvet_taxable_sales_location_idx
  on greendogops.ezyvet_taxable_sales (location_key);
comment on table greendogops.ezyvet_taxable_sales is
  'Tax-code totals for the pulled window, grouped by department (the department section drives location_key). Used for tax remittance and to reconcile taxable vs exempt sales.';

-- ---------------------------------------------------------------------------
-- Disabled Records — ezyVet report "Disabled Records"
-- Audit trail of voided/disabled invoices and payments.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_disabled_record (
  id              uuid primary key default gen_random_uuid(),
  code            text,
  name            text,
  disabled_date   date,
  disabled_at     timestamptz,
  disabled_by     text,

  snapshot_date   date not null,
  period_start    date,
  period_end      date,
  created_at      timestamptz not null default now()
);
create index if not exists ezyvet_disabled_record_date_idx
  on greendogops.ezyvet_disabled_record (disabled_date);
create index if not exists ezyvet_disabled_record_snapshot_idx
  on greendogops.ezyvet_disabled_record (snapshot_date);
comment on table greendogops.ezyvet_disabled_record is
  'Invoices and payments that were disabled (voided), with who did it and when. Financial-control surface: a spike here, or voids by one user, is worth investigating. Usually empty on a normal day.';

-- ---------------------------------------------------------------------------
-- Staff Sales & Gross Profit — ezyVet report "Staff Sales"
-- Per-invoice turnover and GROSS PROFIT credited to the staff member who raised it.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_staff_sale (
  id                uuid primary key default gen_random_uuid(),
  invoice_number    bigint,
  invoiced_at       timestamptz,
  invoice_date      date,
  turnover          numeric,
  gross_profit      numeric,
  gross_profit_pct  numeric,
  staff_member      text,

  snapshot_date     date not null,
  period_start      date,
  period_end        date,
  created_at        timestamptz not null default now()
);
create index if not exists ezyvet_staff_sale_date_idx
  on greendogops.ezyvet_staff_sale (invoice_date);
create index if not exists ezyvet_staff_sale_snapshot_idx
  on greendogops.ezyvet_staff_sale (snapshot_date);
comment on table greendogops.ezyvet_staff_sale is
  'One row per invoice per staff member, with turnover and gross profit in dollars and percent. This is the ONLY source of margin in the warehouse — ezyvet_invoice_line carries revenue but no cost. Note gross profit only counts products that have a cost price and markup. staff_member is the SALESPERSON who raised the invoice, not the case-owning doctor.';

-- ---------------------------------------------------------------------------
-- Customer Invoice Statistics — ezyVet report "Customer Invoice Statistics"
-- Per-client spend, gross profit, invoice counts and averages for the window.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_customer_invoice_stat (
  id                            uuid primary key default gen_random_uuid(),
  business_name                 text,
  first_name                    text,
  last_name                     text,
  email                         text,
  turnover                      numeric,
  gross_profit                  numeric,
  invoice_count                 bigint,
  invoice_line_count            bigint,
  avg_turnover_per_invoice      numeric,
  avg_turnover_per_line         numeric,
  avg_gross_profit_per_invoice  numeric,
  avg_gross_profit_per_line     numeric,

  snapshot_date                 date not null,
  period_start                  date,
  period_end                    date,
  created_at                    timestamptz not null default now()
);
create index if not exists ezyvet_customer_invoice_stat_snapshot_idx
  on greendogops.ezyvet_customer_invoice_stat (snapshot_date);
comment on table greendogops.ezyvet_customer_invoice_stat is
  'Per-client totals for the pulled window: turnover, gross profit, number of invoices and lines, and the averages per invoice and per line. Good for client-value and basket-size questions; matched on name/email since the report does not export the contact code.';

-- ---------------------------------------------------------------------------
-- Appointment Status Timings — ezyVet report "Appointment Status"
-- Per-appointment minutes spent in each status — wait times and throughput.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_appointment_status (
  id                      uuid primary key default gen_random_uuid(),
  division                text,
  animal                  text,
  owner                   text,
  appt_at                 timestamptz,
  appt_date               date,
  mins_no_status          numeric,
  mins_unconfirmed        numeric,
  mins_confirmed          numeric,
  mins_in_transit         numeric,
  mins_in_waiting_room    numeric,
  mins_in_consultation    numeric,
  mins_in_procedure       numeric,
  mins_admit_for_surgery  numeric,
  mins_in_hospital        numeric,
  mins_in_discharge       numeric,
  mins_awaiting_collect   numeric,
  mins_departed           numeric,
  mins_interim_report     numeric,
  mins_referral_done      numeric,
  mins_complete           numeric,
  time_to_complete        text,
  mins_to_complete        numeric,
  location_key            text,

  snapshot_date           date not null,
  period_start            date,
  period_end              date,
  created_at              timestamptz not null default now()
);
create index if not exists ezyvet_appointment_status_date_idx
  on greendogops.ezyvet_appointment_status (appt_date);
create index if not exists ezyvet_appointment_status_snapshot_idx
  on greendogops.ezyvet_appointment_status (snapshot_date);
create index if not exists ezyvet_appointment_status_location_idx
  on greendogops.ezyvet_appointment_status (location_key);
comment on table greendogops.ezyvet_appointment_status is
  'One row per appointment, with the MINUTES it spent in each ezyVet status (mins_in_waiting_room, mins_in_consultation, mins_in_hospital...) and mins_to_complete. This is the operational counterpart to the agenda counts: use it for wait times, room/doctor throughput and how long visit types really take. time_to_complete reads ''Not Complete'' (and mins_to_complete is null) when the appointment was never finished, which is common — filter those out before averaging.';

-- ---------------------------------------------------------------------------
-- Appointment Type Summary — ezyVet report "Appointment Type"
-- Count and average/total minutes per appointment type per hospital.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_appointment_type_stat (
  id              uuid primary key default gen_random_uuid(),
  division        text,
  appt_type       text,
  appt_count      bigint,
  avg_minutes     numeric,
  total_minutes   numeric,
  location_key    text,

  snapshot_date   date not null,
  period_start    date,
  period_end      date,
  created_at      timestamptz not null default now()
);
create index if not exists ezyvet_appointment_type_stat_snapshot_idx
  on greendogops.ezyvet_appointment_type_stat (snapshot_date);
create index if not exists ezyvet_appointment_type_stat_location_idx
  on greendogops.ezyvet_appointment_type_stat (location_key);
comment on table greendogops.ezyvet_appointment_type_stat is
  'Aggregated per appointment type and division for the pulled window: how many were booked and the average and total minutes. Use this to size scheduling templates against how long visits actually take.';

-- ---------------------------------------------------------------------------
-- Unbilled Consults — ezyVet report "Unbilled Consult Appointments"
-- Consult appointments with no invoice — missed charges to chase.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_unbilled_consult (
  id                   uuid primary key default gen_random_uuid(),
  appt_at              timestamptz,
  appt_date            date,
  client_contact_code  text,
  business_name        text,
  first_name           text,
  last_name            text,
  pet_name             text,
  consult_number       bigint,
  appt_type            text,
  consult_division     text,
  reason               text,
  location_key         text,

  snapshot_date        date not null,
  period_start         date,
  period_end           date,
  created_at           timestamptz not null default now()
);
create index if not exists ezyvet_unbilled_consult_date_idx
  on greendogops.ezyvet_unbilled_consult (appt_date);
create index if not exists ezyvet_unbilled_consult_snapshot_idx
  on greendogops.ezyvet_unbilled_consult (snapshot_date);
create index if not exists ezyvet_unbilled_consult_location_idx
  on greendogops.ezyvet_unbilled_consult (location_key);
comment on table greendogops.ezyvet_unbilled_consult is
  'Consults that happened but were never invoiced: the daily missed-revenue worklist. Re-read over a rolling two-week window, so a consult that gets invoiced later simply drops out of the table.';

-- ---------------------------------------------------------------------------
-- Estimates — ezyVet report "Estimate Status"
-- Every estimate and its stage — the quote-to-acceptance funnel.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_estimate (
  id                          uuid primary key default gen_random_uuid(),
  date_sent                   date,
  date_sent_raw               text,
  originator                  text,
  estimate_number             bigint,
  estimate_name               text,
  customer_number             text,
  customer_name               text,
  email                       text,
  status                      text,
  excluded_from_markup_value  numeric,
  product_value               numeric,
  total_value                 numeric,
  next_action_date            date,
  last_comment                text,
  cost_of_estimate            numeric,

  snapshot_date               date not null,
  period_start                date,
  period_end                  date,
  created_at                  timestamptz not null default now()
);
create unique index if not exists ezyvet_estimate_key_idx
  on greendogops.ezyvet_estimate (estimate_number);
create index if not exists ezyvet_estimate_date_idx
  on greendogops.ezyvet_estimate (date_sent);
create index if not exists ezyvet_estimate_snapshot_idx
  on greendogops.ezyvet_estimate (snapshot_date);
comment on table greendogops.ezyvet_estimate is
  'One row per estimate with its status (Created / Sent / Accepted / Declined), value and originating doctor. Conversion rate = accepted value over total value. date_sent is null while the estimate is unsent (date_sent_raw then reads ''Not Sent''). Re-read on a rolling window and upserted, since estimates change status days after they are written.';

-- ---------------------------------------------------------------------------
-- Consult Metrics — ezyVet report "Consult Metrics"
-- Clinical case mix: presenting and master problems per consult and doctor.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_consult_metric (
  id                   uuid primary key default gen_random_uuid(),
  consult_created_at   timestamptz,
  created_date         date,
  consult_number       bigint,
  case_owner           text,
  pet_name             text,
  date_of_birth        date,
  owner                text,
  species              text,
  breed                text,
  weight_lb            numeric,
  master_problems      text,
  presenting_problems  text,

  snapshot_date        date not null,
  period_start         date,
  period_end           date,
  created_at           timestamptz not null default now()
);
create unique index if not exists ezyvet_consult_metric_key_idx
  on greendogops.ezyvet_consult_metric (consult_number);
create index if not exists ezyvet_consult_metric_date_idx
  on greendogops.ezyvet_consult_metric (created_date);
create index if not exists ezyvet_consult_metric_snapshot_idx
  on greendogops.ezyvet_consult_metric (snapshot_date);
comment on table greendogops.ezyvet_consult_metric is
  'One row per clinical record: the case owner, the pet (species, breed, weight, date of birth) and the MASTER and PRESENTING PROBLEMS. This is the only source of what we actually treat, so use it for case-mix, caseload-by-condition and per-doctor clinical questions. Problems are free text and may list several separated by commas, so match with ILIKE.';

-- ---------------------------------------------------------------------------
-- Clinical Note Approval — ezyVet report "Clinical Note Approval"
-- Medical-record completion: which notes are approved, by whom and when.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_clinical_note (
  id                 uuid primary key default gen_random_uuid(),
  record_type        text,
  consult_number     bigint,
  case_owner         text,
  department         text,
  animal_name        text,
  animal_code        text,
  approved_by        text,
  approved_at        timestamptz,
  note_created_by    text,
  note_created_at    timestamptz,
  note_created_date  date,
  modified_by        text,
  modified_at        timestamptz,
  location_key       text,

  snapshot_date      date not null,
  period_start       date,
  period_end         date,
  created_at         timestamptz not null default now()
);
create index if not exists ezyvet_clinical_note_date_idx
  on greendogops.ezyvet_clinical_note (note_created_date);
create index if not exists ezyvet_clinical_note_snapshot_idx
  on greendogops.ezyvet_clinical_note (snapshot_date);
create index if not exists ezyvet_clinical_note_location_idx
  on greendogops.ezyvet_clinical_note (location_key);
comment on table greendogops.ezyvet_clinical_note is
  'One row per clinical note (SOAP and similar) with its approver and created/approved/modified timestamps. approved_by null means the record is still unapproved — the medical-records compliance backlog. Rebuilt over a rolling 30-day window each run.';

-- ---------------------------------------------------------------------------
-- Controlled Drugs — ezyVet report "Controlled Drug"
-- Controlled-substance dispensing log for DEA reporting.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_controlled_drug (
  id                       uuid primary key default gen_random_uuid(),
  dispensed_at             timestamptz,
  dispensed_date           date,
  product_code             text,
  product_name             text,
  prescriber               text,
  prescriber_dea           text,
  dispense_type            text,
  dispensed_qty            numeric,
  qty_on_hand              numeric,
  dispensing_user          text,
  client_code              text,
  client_name              text,
  pet_code                 text,
  pet_name                 text,
  pet_species              text,
  prescription_no          text,
  medication_instructions  text,
  refills_left             bigint,
  days_supply              bigint,
  invoice_no               text,
  invoice_status           text,
  product_schedule_class   text,
  division                 text,
  location_key             text,

  snapshot_date            date not null,
  period_start             date,
  period_end               date,
  created_at               timestamptz not null default now()
);
create index if not exists ezyvet_controlled_drug_date_idx
  on greendogops.ezyvet_controlled_drug (dispensed_date);
create index if not exists ezyvet_controlled_drug_snapshot_idx
  on greendogops.ezyvet_controlled_drug (snapshot_date);
create index if not exists ezyvet_controlled_drug_location_idx
  on greendogops.ezyvet_controlled_drug (location_key);
comment on table greendogops.ezyvet_controlled_drug is
  'Every controlled-substance dispense: product, prescriber and DEA number, quantity, quantity on hand, and the pet/client it was dispensed for. dispensed_qty is negative for a dispense. Client date of birth, phone and address ARE in the ezyVet export but are deliberately not stored. Note ezyVet''s export is column-shifted, so the clinic arrives under its ''Batch'' header and is stored as division; batch number is not available.';

-- ---------------------------------------------------------------------------
-- Vaccinations — ezyVet report "Vaccinations"
-- Vaccinations given, with next-due dates for compliance and recall.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_vaccination (
  id                     uuid primary key default gen_random_uuid(),
  vaccination_id         text,
  creating_user          text,
  created_at_ezyvet      timestamptz,
  modifying_user         text,
  modified_at            timestamptz,
  is_active              boolean,
  sales_resource         text,
  approved_by            text,
  approved_at            timestamptz,
  consult                text,
  external_reference     text,
  animal                 text,
  vaccination_date       date,
  notes                  text,
  vet_user               text,
  product                text,
  quantity               numeric,
  description            text,
  next_date              date,
  send_reminder          boolean,
  is_historical          boolean,
  annual_health_product  text,
  event                  text,

  snapshot_date          date not null,
  period_start           date,
  period_end             date,
  created_at             timestamptz not null default now()
);
create unique index if not exists ezyvet_vaccination_key_idx
  on greendogops.ezyvet_vaccination (vaccination_id);
create index if not exists ezyvet_vaccination_date_idx
  on greendogops.ezyvet_vaccination (vaccination_date);
create index if not exists ezyvet_vaccination_snapshot_idx
  on greendogops.ezyvet_vaccination (snapshot_date);
comment on table greendogops.ezyvet_vaccination is
  'One row per vaccination administered: product, quantity, the vet who gave it, the date, and next_date for the reminder. is_historical marks vaccinations recorded from an outside clinic rather than given here.';

-- ---------------------------------------------------------------------------
-- Standard of Care Overdue — ezyVet report "SOC Overdue with Upcoming Appointments"
-- Pets with overdue standard-of-care items who already have an appointment booked.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_soc_overdue (
  id                     uuid primary key default gen_random_uuid(),
  animal_number          text,
  animal_name            text,
  species                text,
  breed                  text,
  owner_first_name       text,
  owner_last_name        text,
  phone_numbers          text,
  mobile_numbers         text,
  email_addresses        text,
  soc_treatment          text,
  soc_type               text,
  soc_due_date           date,
  days_overdue           bigint,
  last_fulfilled_date    date,
  appt_date              date,
  days_until_appt        bigint,
  appt_duration_minutes  bigint,
  appt_reason            text,
  appt_status            text,
  appt_type              text,
  soc_created_date       date,
  department             text,
  location_key           text,

  snapshot_date          date not null,
  period_start           date,
  period_end             date,
  created_at             timestamptz not null default now()
);
create index if not exists ezyvet_soc_overdue_snapshot_idx
  on greendogops.ezyvet_soc_overdue (snapshot_date);
create index if not exists ezyvet_soc_overdue_location_idx
  on greendogops.ezyvet_soc_overdue (location_key);
comment on table greendogops.ezyvet_soc_overdue is
  'The pre-visit preparation worklist: pets with an overdue standard-of-care item (vaccine, test, treatment) AND an upcoming appointment, so the team can add it before the visit. days_overdue is how late the item is, days_until_appt how soon they are coming in. Daily snapshot — filter to the latest snapshot_date, and note the same pet appears once per overdue item.';

-- ---------------------------------------------------------------------------
-- Wellness Plan Use — ezyVet report "Wellness Plan Use"
-- Membership benefit utilisation: what is allocated, used and remaining.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_wellness_plan_use (
  id               uuid primary key default gen_random_uuid(),
  unique_id        text,
  customer_code    text,
  customer_name    text,
  pet_code         text,
  pet_name         text,
  plan             text,
  department       text,
  term_start_date  date,
  benefit          text,
  benefit_type     text,
  saved            numeric,
  allocated        numeric,
  used             numeric,
  available        numeric,
  location_key     text,

  snapshot_date    date not null,
  period_start     date,
  period_end       date,
  created_at       timestamptz not null default now()
);
create unique index if not exists ezyvet_wellness_plan_use_key_idx
  on greendogops.ezyvet_wellness_plan_use (unique_id, snapshot_date);
create index if not exists ezyvet_wellness_plan_use_snapshot_idx
  on greendogops.ezyvet_wellness_plan_use (snapshot_date);
create index if not exists ezyvet_wellness_plan_use_location_idx
  on greendogops.ezyvet_wellness_plan_use (location_key);
comment on table greendogops.ezyvet_wellness_plan_use is
  'One row per pet per plan benefit per snapshot: allocated, used and available. Unused ''available'' benefits are the practice''s outstanding liability and the reason to recall the client. Large table (~20k rows per snapshot), so always filter to one snapshot_date and aggregate.';

-- ---------------------------------------------------------------------------
-- Inventory Value — ezyVet report "Inventory Value"
-- Stock on hand and the dollars tied up in it, per product per day.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_inventory_value (
  id                      uuid primary key default gen_random_uuid(),
  product_code            text,
  product_name            text,
  product_group           text,
  current_unit_cost       numeric,
  weighted_avg_unit_cost  numeric,
  qty_in_inventory        numeric,
  total_inventory_value   numeric,

  snapshot_date           date not null,
  period_start            date,
  period_end              date,
  created_at              timestamptz not null default now()
);
create unique index if not exists ezyvet_inventory_value_key_idx
  on greendogops.ezyvet_inventory_value (product_code, snapshot_date);
create index if not exists ezyvet_inventory_value_snapshot_idx
  on greendogops.ezyvet_inventory_value (snapshot_date);
comment on table greendogops.ezyvet_inventory_value is
  'Daily snapshot of stocked products: quantity in inventory, current and weighted-average unit cost, and total value. Trend total_inventory_value by snapshot_date for stock levels over time. Negative quantities are real in ezyVet (items sold that were never received) and flag count errors.';

-- ---------------------------------------------------------------------------
-- Expiring Inventory — ezyVet report "Expiring Inventory"
-- Batches expiring in the next six months — waste prevention worklist.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_expiring_inventory (
  id                    uuid primary key default gen_random_uuid(),
  product_code          text,
  product_name          text,
  supplier_name         text,
  batch_number          text,
  expiry_date           date,
  qty_in_stock          numeric,
  qty_available         numeric,
  total_available_cost  numeric,
  location_name         text,

  snapshot_date         date not null,
  period_start          date,
  period_end            date,
  created_at            timestamptz not null default now()
);
create index if not exists ezyvet_expiring_inventory_snapshot_idx
  on greendogops.ezyvet_expiring_inventory (snapshot_date);
comment on table greendogops.ezyvet_expiring_inventory is
  'Product batches with an expiry date inside the look-ahead window, with quantity and the cost at risk. Daily snapshot; use the latest snapshot_date and order by expiry_date to work the list.';

-- ---------------------------------------------------------------------------
-- Expired Inventory — ezyVet report "Expired Inventory"
-- Batches already past their expiry date that are still in stock.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_expired_inventory (
  id              uuid primary key default gen_random_uuid(),
  product_code    text,
  product_name    text,
  supplier        text,
  batch_number    text,
  expiry_date     date,
  qty_in_stock    numeric,

  snapshot_date   date not null,
  period_start    date,
  period_end      date,
  created_at      timestamptz not null default now()
);
create index if not exists ezyvet_expired_inventory_snapshot_idx
  on greendogops.ezyvet_expired_inventory (snapshot_date);
comment on table greendogops.ezyvet_expired_inventory is
  'Stock that has already expired and should be pulled and written off. Daily snapshot — anything appearing here is a live problem.';

-- ---------------------------------------------------------------------------
-- Inventory Ordering — ezyVet report "Inventory Ordering"
-- Reorder worklist with stock turns: what to order and how fast it moves.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_inventory_ordering (
  id                   uuid primary key default gen_random_uuid(),
  product_code         text,
  product_name         text,
  in_inventory         numeric,
  available            numeric,
  ordered              numeric,
  receipting           numeric,
  short                numeric,
  to_order             numeric,
  turn_last_month      numeric,
  turn_last_12_months  numeric,
  avg_monthly_turn     numeric,

  snapshot_date        date not null,
  period_start         date,
  period_end           date,
  created_at           timestamptz not null default now()
);
create unique index if not exists ezyvet_inventory_ordering_key_idx
  on greendogops.ezyvet_inventory_ordering (product_code, snapshot_date);
create index if not exists ezyvet_inventory_ordering_snapshot_idx
  on greendogops.ezyvet_inventory_ordering (snapshot_date);
comment on table greendogops.ezyvet_inventory_ordering is
  'Daily snapshot of the ordering position per product: in inventory, available, on order, receipting, short, and to_order, plus inventory turns for last month, the last 12 months and the monthly average. to_order > 0 is the buy list; low turns with high stock is dead money.';

-- ---------------------------------------------------------------------------
-- Inventory Transfers — ezyVet report "Inventory Transfer"
-- Stock moved between locations, with reason and value.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_inventory_transfer (
  id                   uuid primary key default gen_random_uuid(),
  transfer_number      text,
  product_code         text,
  product_name         text,
  product_description  text,
  transferred_at       timestamptz,
  transfer_date        date,
  created_by           text,
  inventory_location   text,
  last_modified        text,
  reason               text,
  quantity             numeric,
  batch                text,
  account              text,
  in_inventory         numeric,
  available            numeric,
  per_unit_cost        numeric,
  total                numeric,
  location_key         text,

  snapshot_date        date not null,
  period_start         date,
  period_end           date,
  created_at           timestamptz not null default now()
);
create index if not exists ezyvet_inventory_transfer_date_idx
  on greendogops.ezyvet_inventory_transfer (transfer_date);
create index if not exists ezyvet_inventory_transfer_snapshot_idx
  on greendogops.ezyvet_inventory_transfer (snapshot_date);
create index if not exists ezyvet_inventory_transfer_location_idx
  on greendogops.ezyvet_inventory_transfer (location_key);
comment on table greendogops.ezyvet_inventory_transfer is
  'Stock movements between inventory locations: product, quantity, reason, per-unit cost and total. Explains why a clinic''s stock changed without a sale, and surfaces stock quietly shifting between hospitals.';

-- ---------------------------------------------------------------------------
-- Purchases — ezyVet report "Purchases"
-- What was bought from suppliers: product, quantity and spend.
-- ---------------------------------------------------------------------------
create table if not exists greendogops.ezyvet_purchase (
  id                       uuid primary key default gen_random_uuid(),
  purchase_date            date,
  receive_invoice          text,
  supplier_invoice_number  text,
  purchase_for             text,
  purchase_orders          text,
  product_code             text,
  product_name             text,
  supplier_code            text,
  qty                      numeric,
  unit_price_excl          numeric,
  unit_price_incl          numeric,
  total_excl               numeric,
  total_incl               numeric,
  location_key             text,

  snapshot_date            date not null,
  period_start             date,
  period_end               date,
  created_at               timestamptz not null default now()
);
create index if not exists ezyvet_purchase_date_idx
  on greendogops.ezyvet_purchase (purchase_date);
create index if not exists ezyvet_purchase_snapshot_idx
  on greendogops.ezyvet_purchase (snapshot_date);
create index if not exists ezyvet_purchase_location_idx
  on greendogops.ezyvet_purchase (location_key);
comment on table greendogops.ezyvet_purchase is
  'Purchase-order lines received from suppliers over a rolling window: product, quantity, unit price and totals excluding and including tax. The source for supplier spend and COGS-side questions; ties to the vendor CRM by supplier code.';

-- ---------------------------------------------------------------------------
-- Roll-up views. The Smart Report is told to prefer report_* views so its
-- answers match what the app shows. Snapshot reports expose a "_current" view
-- that pins the latest pull, because querying the raw table without filtering
-- snapshot_date silently multiplies every total by the number of days ingested.
-- ---------------------------------------------------------------------------
create or replace view greendogops.report_daily_collections as
select payment_date,
       location_key,
       coalesce(nullif(payment_method, ''), 'Unknown') as payment_method,
       count(*)          as payment_count,
       sum(amount)       as collected,
       sum(surcharge)    as surcharge
from greendogops.ezyvet_payment
where payment_date is not null
group by 1, 2, 3;

create or replace view greendogops.report_ar_aging_current as
select r.*
from greendogops.ezyvet_aged_receivable r
join (select max(snapshot_date) as d from greendogops.ezyvet_aged_receivable) m
  on r.snapshot_date = m.d;

create or replace view greendogops.report_ar_aging_trend as
select snapshot_date,
       count(*)               as clients_owing,
       sum(total_due)         as total_due,
       sum(bucket_current)    as due_current,
       sum(bucket_30)         as due_30,
       sum(bucket_60)         as due_60,
       sum(bucket_90_plus)    as due_90_plus
from greendogops.ezyvet_aged_receivable
group by 1;

create or replace view greendogops.report_appointment_flow as
select appt_date,
       location_key,
       count(*)                                          as appointments,
       round(avg(mins_in_waiting_room)::numeric, 1)      as avg_wait_minutes,
       round(avg(mins_in_consultation)::numeric, 1)      as avg_consult_minutes,
       round(avg(mins_in_hospital)::numeric, 1)          as avg_hospital_minutes,
       round(avg(mins_to_complete)::numeric, 1)          as avg_minutes_to_complete,
       count(*) filter (where mins_to_complete is null)  as never_completed
from greendogops.ezyvet_appointment_status
where appt_date is not null
group by 1, 2;

create or replace view greendogops.report_unbilled_consults_current as
select c.*
from greendogops.ezyvet_unbilled_consult c
join (select max(snapshot_date) as d from greendogops.ezyvet_unbilled_consult) m
  on c.snapshot_date = m.d;

create or replace view greendogops.report_estimate_conversion as
select date_trunc('month', coalesce(date_sent, period_end))::date as month,
       status,
       count(*)          as estimates,
       sum(total_value)  as total_value
from greendogops.ezyvet_estimate
group by 1, 2;

create or replace view greendogops.report_clinical_note_backlog as
select coalesce(nullif(case_owner, ''), nullif(note_created_by, ''), 'Unassigned') as clinician,
       location_key,
       count(*) filter (where approved_by is null) as unapproved_notes,
       count(*)                                    as total_notes,
       min(note_created_date) filter (where approved_by is null) as oldest_unapproved
from greendogops.ezyvet_clinical_note
group by 1, 2;

create or replace view greendogops.report_soc_overdue_current as
select s.*
from greendogops.ezyvet_soc_overdue s
join (select max(snapshot_date) as d from greendogops.ezyvet_soc_overdue) m
  on s.snapshot_date = m.d;

create or replace view greendogops.report_inventory_on_hand as
select v.*
from greendogops.ezyvet_inventory_value v
join (select max(snapshot_date) as d from greendogops.ezyvet_inventory_value) m
  on v.snapshot_date = m.d;

create or replace view greendogops.report_inventory_value_trend as
select snapshot_date,
       count(*)                     as products,
       sum(total_inventory_value)   as inventory_value
from greendogops.ezyvet_inventory_value
group by 1;

create or replace view greendogops.report_reorder_list as
select o.product_code, o.product_name, o.in_inventory, o.available, o.ordered,
       o.short, o.to_order, o.turn_last_month, o.turn_last_12_months,
       o.avg_monthly_turn, o.snapshot_date
from greendogops.ezyvet_inventory_ordering o
join (select max(snapshot_date) as d from greendogops.ezyvet_inventory_ordering) m
  on o.snapshot_date = m.d
where o.to_order > 0;

create or replace view greendogops.report_wellness_plan_current as
select w.*
from greendogops.ezyvet_wellness_plan_use w
join (select max(snapshot_date) as d from greendogops.ezyvet_wellness_plan_use) m
  on w.snapshot_date = m.d;

grant select on
  greendogops.report_daily_collections,
  greendogops.report_ar_aging_current,
  greendogops.report_ar_aging_trend,
  greendogops.report_appointment_flow,
  greendogops.report_unbilled_consults_current,
  greendogops.report_estimate_conversion,
  greendogops.report_clinical_note_backlog,
  greendogops.report_soc_overdue_current,
  greendogops.report_inventory_on_hand,
  greendogops.report_inventory_value_trend,
  greendogops.report_reorder_list,
  greendogops.report_wellness_plan_current
to service_role;


-- ---------------------------------------------------------------------------
-- A dedicated agent for the long tail, so a failure here can never jeopardise
-- the core invoice/patient ingest run by ezyvet_daily_ingest.
-- ---------------------------------------------------------------------------
insert into greendogops.agent (key, name, description, schedule_cron, timezone, enabled)
values ('ezyvet_extra_reports', 'ezyVet Extra Reports',
        'Payments, receivables, daily close, appointment timings, clinical compliance and inventory pulled from the ezyVet Report Center.',
        '30 12 * * *', 'America/Los_Angeles', true)
on conflict (key) do nothing;

insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'payment_summary', 'Payments', 'global',
       'Every payment taken, by method and hospital — what was actually COLLECTED.', 'ezyvet_payment', 1
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'payment_allocations', 'Payment Allocations', 'global',
       'How each payment was split across hospitals/divisions.', 'ezyvet_payment_allocation', 2
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'aged_receivables', 'Aged Receivables', 'global',
       'Client accounts receivable, aged into 30/60/90+ day buckets.', 'ezyvet_aged_receivable', 3
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'end_of_day_totals', 'End of Day Totals', 'global',
       'Daily close: pending vs approved invoices, payments by type, debtor balances.', 'ezyvet_end_of_day', 4
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'invoice_credit_summary', 'Invoices & Credits', 'global',
       'Invoice-header level view: status, credits, amount due, pet and insurance.', 'ezyvet_invoice_summary', 5
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'unapplied_payments', 'Unapplied Payments & Credits', 'global',
       'Client money received but not yet allocated to an invoice.', 'ezyvet_unapplied_payment', 6
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'taxable_sales', 'Taxable Sales', 'global',
       'Invoiced totals and tax collected per tax code, per department.', 'ezyvet_taxable_sales', 7
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'disabled_records', 'Disabled Records', 'global',
       'Audit trail of voided/disabled invoices and payments.', 'ezyvet_disabled_record', 8
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'staff_sales', 'Staff Sales & Gross Profit', 'global',
       'Per-invoice turnover and GROSS PROFIT credited to the staff member who raised it.', 'ezyvet_staff_sale', 9
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'customer_invoice_statistics', 'Customer Invoice Statistics', 'global',
       'Per-client spend, gross profit, invoice counts and averages for the window.', 'ezyvet_customer_invoice_stat', 10
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'appointment_status', 'Appointment Status Timings', 'global',
       'Per-appointment minutes spent in each status — wait times and throughput.', 'ezyvet_appointment_status', 11
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'appointment_type', 'Appointment Type Summary', 'global',
       'Count and average/total minutes per appointment type per hospital.', 'ezyvet_appointment_type_stat', 12
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'unbilled_consults', 'Unbilled Consults', 'global',
       'Consult appointments with no invoice — missed charges to chase.', 'ezyvet_unbilled_consult', 13
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'estimate_status', 'Estimates', 'global',
       'Every estimate and its stage — the quote-to-acceptance funnel.', 'ezyvet_estimate', 14
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'consult_metrics', 'Consult Metrics', 'global',
       'Clinical case mix: presenting and master problems per consult and doctor.', 'ezyvet_consult_metric', 15
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'clinical_note_approval', 'Clinical Note Approval', 'global',
       'Medical-record completion: which notes are approved, by whom and when.', 'ezyvet_clinical_note', 16
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'controlled_drug', 'Controlled Drugs', 'global',
       'Controlled-substance dispensing log for DEA reporting.', 'ezyvet_controlled_drug', 17
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'vaccinations', 'Vaccinations', 'global',
       'Vaccinations given, with next-due dates for compliance and recall.', 'ezyvet_vaccination', 18
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'soc_overdue', 'Standard of Care Overdue', 'global',
       'Pets with overdue standard-of-care items who already have an appointment booked.', 'ezyvet_soc_overdue', 19
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'wellness_plan_use', 'Wellness Plan Use', 'global',
       'Membership benefit utilisation: what is allocated, used and remaining.', 'ezyvet_wellness_plan_use', 20
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'inventory_value', 'Inventory Value', 'global',
       'Stock on hand and the dollars tied up in it, per product per day.', 'ezyvet_inventory_value', 21
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'expiring_inventory', 'Expiring Inventory', 'global',
       'Batches expiring in the next six months — waste prevention worklist.', 'ezyvet_expiring_inventory', 22
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'expired_inventory', 'Expired Inventory', 'global',
       'Batches already past their expiry date that are still in stock.', 'ezyvet_expired_inventory', 23
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'inventory_ordering', 'Inventory Ordering', 'global',
       'Reorder worklist with stock turns: what to order and how fast it moves.', 'ezyvet_inventory_ordering', 24
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'inventory_transfer', 'Inventory Transfers', 'global',
       'Stock moved between locations, with reason and value.', 'ezyvet_inventory_transfer', 25
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
insert into greendogops.agent_report (agent_id, key, name, scope, description, target, sort_order)
select a.id, 'purchases', 'Purchases', 'global',
       'What was bought from suppliers: product, quantity and spend.', 'ezyvet_purchase', 26
from greendogops.agent a
where a.key = 'ezyvet_extra_reports'
on conflict (agent_id, key) do nothing;
