-- ============================================================================
-- Green Dog Ops — 0220 One-time Recruiting Pipeline cleanup
-- ----------------------------------------------------------------------------
-- Hand entry and job-board posting titles left person_recruiting with many
-- near-duplicate values ("Veterinary Receptionist" / "Receptionist" /
-- "In-House CSR", "Pass" / "No hire" / "Not moving forward", zip-code
-- variants of the same clinic…). Collapse every column the ATS filters on onto
-- the canonical vocabulary in src/lib/ats/normalize.ts, which every write path
-- now also applies so the duplicates don't come back.
--
--   Position   81 -> 24 distinct      Source      26 -> 15
--   Stage      34 -> 17               Applied to   7 -> 5 (clinic names)
--   Pipeline   11 -> 9
--
-- The value lists below were generated by running the normalizer over the
-- live distinct values. Ambiguous legacy shorthand (DA, DH, Legal, "Entry
-- Level Opportunities") is left as-is. The original values are kept in
-- person_recruiting_cleanup_0220 so the cleanup can be audited or reverted.
-- updated_at is left untouched: this is not a recruiter edit.
-- ============================================================================

set search_path = greendogops, public;

begin;

-- ---------------------------------------------------------------------------
-- 0. Snapshot the original values (first run only). Service-role access only.
-- ---------------------------------------------------------------------------
create table if not exists person_recruiting_cleanup_0220 as
select person_id, target_title, stage, source, source_detail, job_location,
       pipeline, status_notes, now() as backed_up_at
from person_recruiting;

alter table person_recruiting_cleanup_0220 enable row level security;
revoke all on person_recruiting_cleanup_0220 from anon, authenticated;

alter table person_recruiting disable trigger set_updated_at;

-- ---------------------------------------------------------------------------
-- 1. Positions that embedded the clinic: keep the clinic as "Applied to"
--    before the title is collapsed (only when no location is recorded).
-- ---------------------------------------------------------------------------
update person_recruiting set job_location = 'Sherman Oaks'
where job_location is null and target_title in ('CSR - SO', 'Vet Tech - SO');

update person_recruiting set job_location = 'Venice'
where job_location is null
  and target_title in ('CSR - Venice', 'Fac - Venice', 'Summer INTERN (CSR) Venice');

-- ---------------------------------------------------------------------------
-- 2. "DO NOT CONTACT AGAIN" becomes Passed; keep the warning in status notes.
-- ---------------------------------------------------------------------------
update person_recruiting
set status_notes = concat_ws(e'\n', nullif(status_notes, ''), 'DO NOT CONTACT AGAIN')
where stage = 'DO NOT CONTACT AGAIN';

-- ---------------------------------------------------------------------------
-- 3. Keep the specific source (referral-bonus month, recruiter, school…) in
--    source_detail before the source collapses onto its canonical channel.
-- ---------------------------------------------------------------------------
update person_recruiting r
set source_detail = concat_ws(' · ', r.source, nullif(r.source_detail, ''))
from (values
  ('BONUS in FEB 2024', 'Personal Referral'),
  ('BONUS in Jan 24''', 'Personal Referral'),
  ('BONUS in July ''23', 'Personal Referral'),
  ('BONUS in March 24', 'Personal Referral'),
  ('College Network', 'College / School'),
  ('Doc', 'Personal Referral'),
  ('Laurence - Visited Clinic', 'Walk-in'),
  ('Linkedin (Nick)', 'LinkedIn'),
  ('MASH', 'Other'),
  ('Nick', 'Recruiter Outreach'),
  ('Nick college post', 'College / School'),
  ('Nick social media', 'Social Media'),
  ('VCN', 'Other'),
  ('walk', 'Walk-in'),
  ('Western Student', 'College / School')
) as m(old_value, new_value)
where r.source = m.old_value;

-- ---------------------------------------------------------------------------
-- 4. Position (target_title): 63 variant(s) -> canonical.
-- ---------------------------------------------------------------------------
update person_recruiting r
set target_title = m.new_value
from (values
  ('Admin', 'Executive Assistant'),
  ('Asistente de Limpieza', 'Facilities / Cleaning'),
  ('Asistente de Limpieza, Clínica Veterinaria', 'Facilities / Cleaning'),
  ('Assistant', 'Vet Assistant'),
  ('CAREER VET CSR', 'CSR'),
  ('Cleaning service', 'Facilities / Cleaning'),
  ('Client Service Representative', 'CSR'),
  ('CSR - SO', 'CSR'),
  ('CSR - Venice', 'CSR'),
  ('CSR/Vet Tech', 'Vet Tech'),
  ('CT', 'Clinic Tech'),
  ('Driver/Asst', 'Mobile Vet Tech / Driver'),
  ('DVM Extern', 'Extern'),
  ('DVM/Mentorship', 'DVM'),
  ('DVM/Vet Tech', 'DVM'),
  ('Externships', 'Extern'),
  ('Fac', 'Facilities / Cleaning'),
  ('Fac - Venice', 'Facilities / Cleaning'),
  ('Head Veterinarian Tech/HR manager/Payroll Manager', 'Practice Manager'),
  ('Hospital Manager', 'Practice Manager'),
  ('In-House CSR', 'CSR'),
  ('Internships', 'Intern'),
  ('Janitor', 'Facilities / Cleaning'),
  ('Lead Vet Tech', 'Senior Vet Tech'),
  ('Licensed/Certified Veterinary Technician - SeaWorld San Antonio', 'RVT'),
  ('Maintenance', 'Facilities / Cleaning'),
  ('Marketing & Events Coordinator - Venice & Sherman Oaks', 'Marketing'),
  ('Marketing Director', 'Marketing'),
  ('Mobile Veterinary Technician / Driver', 'Mobile Vet Tech / Driver'),
  ('MPMV', 'Mobile Vet Tech / Driver'),
  ('MY PET Tech/CSR', 'Mobile Vet Tech / Driver'),
  ('NAD Tech', 'Dental Tech'),
  ('NON-ANESTHETIC PET DENTAL TECHNICIAN', 'Dental Tech'),
  ('Non-Anesthetic Pet Dental Technician - Sherman Oaks', 'Dental Tech'),
  ('Office Manager', 'Practice Manager'),
  ('Overnight ER Manager', 'Practice Manager'),
  ('Personal Asst. ap', 'Executive Assistant'),
  ('Practice Manager - Long Beach', 'Practice Manager'),
  ('Practice Office Manager', 'Practice Manager'),
  ('Receptionist', 'CSR'),
  ('Recruiting Asst', 'Recruiting Assistant'),
  ('Remote', 'Remote CSR'),
  ('Remote CSR - Client Service Representative', 'Remote CSR'),
  ('Remote customer service', 'Remote CSR'),
  ('Remote receptionist', 'Remote CSR'),
  ('Remote Receptionist', 'Remote CSR'),
  ('Remote Vet Receptionist', 'Remote CSR'),
  ('Remote Veterinary Receptionist', 'Remote CSR'),
  ('REMOTE VETERINARY RECEPTIONIST', 'Remote CSR'),
  ('Remote Veterinary Receptionist Csr', 'Remote CSR'),
  ('Senior Veterinary Technician', 'Senior Vet Tech'),
  ('Summer INTERN (CSR) Venice', 'Intern'),
  ('Vet assistant /reception', 'Vet Assistant'),
  ('Vet Tech - SO', 'Vet Tech'),
  ('VET TECH & Prevet student', 'Vet Tech'),
  ('Veterinarian', 'DVM'),
  ('Veterinary Assistant', 'Vet Assistant'),
  ('Veterinary Assistant/Technician', 'Vet Assistant'),
  ('Veterinary Receptionist', 'CSR'),
  ('Veterinary Technician', 'Vet Tech'),
  ('Veterinary Technician / Practice Manager', 'Practice Manager'),
  ('VETERINARY/ ANIMAL CARE SPECIALIST /COORDINATOR', 'Vet Assistant'),
  ('Western University Rotating Internship -2026', 'Intern')
) as m(old_value, new_value)
where r.target_title = m.old_value;

-- ---------------------------------------------------------------------------
-- 5. Stage: 23 variant(s) -> canonical.
-- ---------------------------------------------------------------------------
update person_recruiting r
set stage = m.new_value
from (values
  ('Applicant', 'New Lead'),
  ('Contacting', 'Contacted'),
  ('Decision needed', 'Decision Needed'),
  ('Declined Offer', 'Offer Declined'),
  ('Did not respond', 'No Response'),
  ('DO NOT CONTACT AGAIN', 'Passed'),
  ('Hire', 'Hired'),
  ('Hold', 'Hold for Future'),
  ('Hold For Future', 'Hold for Future'),
  ('In Person / Shadow', 'In-Person / Shadow Day'),
  ('Lead', 'New Lead'),
  ('No hire', 'Passed'),
  ('No Longer With Us', 'Separated'),
  ('No response', 'No Response'),
  ('Not moving forward', 'Passed'),
  ('Pass', 'Passed'),
  ('Phone Interview', 'Phone Screen'),
  ('Quit', 'Separated'),
  ('QUIT', 'Separated'),
  ('Remain in Contact', 'Hold for Future'),
  ('Reviewed', 'New Lead'),
  ('Seperated ( No Rehire )', 'Separated (No Rehire)'),
  ('Shadow Interview', 'In-Person / Shadow Day')
) as m(old_value, new_value)
where r.stage = m.old_value;

-- ---------------------------------------------------------------------------
-- 6. Source: 16 variant(s) -> canonical.
-- ---------------------------------------------------------------------------
update person_recruiting r
set source = m.new_value
from (values
  ('BONUS in FEB 2024', 'Personal Referral'),
  ('BONUS in Jan 24''', 'Personal Referral'),
  ('BONUS in July ''23', 'Personal Referral'),
  ('BONUS in March 24', 'Personal Referral'),
  ('College Network', 'College / School'),
  ('Doc', 'Personal Referral'),
  ('Laurence - Visited Clinic', 'Walk-in'),
  ('Linkedin (Nick)', 'LinkedIn'),
  ('MASH', 'Other'),
  ('Nick', 'Recruiter Outreach'),
  ('Nick college post', 'College / School'),
  ('Nick social media', 'Social Media'),
  ('VCN', 'Other'),
  ('walk', 'Walk-in'),
  ('Western Student', 'College / School'),
  ('Yes', null)
) as m(old_value, new_value)
where r.source = m.old_value;

-- ---------------------------------------------------------------------------
-- 7. Applied to (job_location): 5 variant(s) -> canonical.
-- ---------------------------------------------------------------------------
update person_recruiting r
set job_location = m.new_value
from (values
  ('Sherman Oaks, CA 91423', 'Sherman Oaks'),
  ('Van Nuys, CA 91401', 'Van Nuys'),
  ('Van Nuys, CA 91411', 'Van Nuys'),
  ('Venice, CA 90291', 'Venice'),
  ('Venice, CA 90294', 'Venice')
) as m(old_value, new_value)
where r.job_location = m.old_value;

-- ---------------------------------------------------------------------------
-- 8. Pipeline: 2 variant(s) -> canonical.
-- ---------------------------------------------------------------------------
update person_recruiting r
set pipeline = m.new_value
from (values
  ('All In House Positions, Remote CSR', 'All In House Positions'),
  ('Remote CSR, Hired', 'Hired')
) as m(old_value, new_value)
where r.pipeline = m.old_value;

alter table person_recruiting enable trigger set_updated_at;

commit;
