-- ============================================================================
-- Staging bootstrap — run BEFORE supabase/migrations/* on a fresh project.
-- ----------------------------------------------------------------------------
-- Migrations 0008/0009 build greendogops.referral_partners and friends with
-- `LIKE public.<table>`. Those source tables belong to the EmployeeGMGDD app and
-- exist only in production, so a fresh project needs empty stand-ins with the
-- same column definitions. Structure only — never any rows.
--
-- Regenerate from production with scripts/gen_staging_shim.sh.
-- ============================================================================

do $$ begin create type public.influencer_status as enum ('active', 'prospect', 'inactive', 'completed'); exception when duplicate_object then null; end $$;

create table if not exists public.clinic_visits (
  id uuid default gen_random_uuid() not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  user_id uuid not null,
  profile_id uuid,
  partner_id uuid,
  clinic_name text not null,
  visit_date date default CURRENT_DATE not null,
  spoke_to text,
  items_discussed text[] default '{}'::text[],
  next_visit_date date,
  visit_notes text,
  logged_via text default 'web'::text,
  is_archived boolean default false
);

create table if not exists public.marketing_influencers (
  id uuid default gen_random_uuid() not null,
  contact_name text not null,
  pet_name text,
  phone text,
  email text,
  status influencer_status default 'prospect'::influencer_status not null,
  agreement_details text,
  promo_code text,
  instagram_handle text,
  instagram_url text,
  facebook_url text,
  tiktok_handle text,
  youtube_url text,
  follower_count integer,
  highest_platform text,
  engagement_rate numeric(5,2),
  location text,
  ezyvet_tracking text,
  notes text,
  last_post_date date,
  posts_completed integer default 0,
  stories_completed integer default 0,
  reels_completed integer default 0,
  events_attended text[],
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  created_by uuid,
  tier text default 'micro'::text,
  content_niche text,
  audience_age_range text,
  audience_gender_split text,
  audience_location text,
  instagram_followers integer,
  tiktok_followers integer,
  youtube_subscribers integer,
  facebook_followers integer,
  avg_likes integer,
  avg_comments integer,
  avg_saves integer,
  avg_shares integer,
  avg_views integer,
  relationship_status text default 'new'::text,
  relationship_score integer default 50,
  last_contact_date date,
  next_followup_date date,
  needs_followup boolean default false,
  priority text default 'medium'::text,
  collaboration_type text,
  content_rights text,
  exclusivity_terms text,
  contract_start_date date,
  contract_end_date date,
  compensation_type text,
  compensation_rate numeric(10,2),
  commission_percentage numeric(5,2),
  total_paid numeric(10,2) default 0,
  total_value_generated numeric(10,2) default 0,
  total_campaigns integer default 0,
  total_impressions bigint default 0,
  total_clicks integer default 0,
  total_conversions integer default 0,
  conversion_rate numeric(5,2),
  roi numeric(5,2),
  preferred_content_types text[],
  content_guidelines text,
  brand_alignment_score integer,
  pet_breed text,
  pet_age text,
  pet_type text,
  pet_instagram text,
  media_kit_url text,
  profile_image_url text,
  bio text,
  source text,
  referral_source text,
  discovered_via text,
  tags text[]
);

create table if not exists public.partner_contacts (
  id uuid default gen_random_uuid() not null,
  partner_id uuid not null,
  name text not null,
  title text,
  email text,
  phone text,
  is_primary boolean default false,
  relationship_notes text,
  preferred_contact_method text default 'email'::text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table if not exists public.partner_notes (
  id uuid default gen_random_uuid() not null,
  partner_id uuid not null,
  note_type text default 'general'::text,
  content text not null,
  is_pinned boolean default false,
  created_by uuid,
  created_by_name text,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  author_initials text,
  edited_at timestamp with time zone,
  edited_by uuid,
  edited_by_initials text,
  category text
);

create table if not exists public.referral_partners (
  id uuid default gen_random_uuid() not null,
  hospital_name text not null,
  contact_person text,
  email text,
  phone text,
  address text,
  tier text default 'bronze'::text not null,
  total_referrals integer default 0 not null,
  notes text,
  is_active boolean default true not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null,
  key_decision_maker text,
  key_decision_maker_title text,
  key_decision_maker_email text,
  key_decision_maker_phone text,
  preferences jsonb default '{}'::jsonb,
  communication_preference text default 'email'::text,
  relationship_status text default 'new'::text,
  last_contact_date date,
  next_followup_date date,
  specialty_areas text[],
  referral_value_monthly numeric(10,2),
  contract_end_date date,
  status text default 'active'::text,
  category text,
  website text,
  description text,
  icon text default 'mdi-factory'::text,
  color text default 'grey'::text,
  products text[] default '{}'::text[],
  revenue_ytd numeric(12,2) default 0,
  revenue_last_year numeric(12,2) default 0,
  average_monthly_revenue numeric(10,2) default 0,
  priority text default 'medium'::text,
  zone text,
  clinic_type text default 'general'::text,
  size text default 'small'::text,
  monthly_referral_goal integer default 0,
  quarterly_revenue_goal numeric(12,2) default 0,
  current_month_referrals integer default 0,
  current_quarter_revenue numeric(12,2) default 0,
  visit_frequency text default 'monthly'::text,
  last_visit_date date,
  preferred_visit_day text,
  preferred_visit_time text,
  best_contact_person text,
  needs_followup boolean default false,
  followup_reason text,
  referral_agreement_type text default 'none'::text,
  ce_event_host boolean default false,
  lunch_and_learn_eligible boolean default true,
  drop_off_materials boolean default true,
  tags text[] default '{}'::text[],
  name text default 'Unknown'::text not null,
  contact_name text,
  deleted_at timestamp with time zone,
  partner_type text default 'clinic'::text,
  events_attended text[] default '{}'::text[],
  is_confirmed boolean default false,
  booth_size text,
  total_referrals_ytd integer default 0,
  total_referrals_all_time integer default 0,
  relationship_score integer default 50,
  preferred_contact_time text,
  instagram_handle text,
  facebook_url text,
  linkedin_url text,
  payment_status text,
  payment_amount numeric(10,2),
  payment_date date,
  organization_type text,
  employee_count text,
  total_revenue_all_time numeric(12,2) default 0.00,
  last_sync_date timestamp with time zone,
  visit_overdue boolean default false,
  expected_visit_frequency_days integer default 180,
  days_since_last_visit integer,
  visit_tier text default 'Low'::text,
  relationship_health integer default 50,
  last_referral_date timestamp with time zone,
  last_data_source text default 'manual'::text,
  referral_divisions text[] default '{}'::text[],
  services text[] default '{}'::text[],
  latitude numeric,
  longitude numeric,
  place_id text,
  geocoded_address text,
  service_radius_km numeric default 25,
  referrals_last_12_months integer default 0
);

create table if not exists public.referral_revenue_line_items (
  id uuid default gen_random_uuid() not null,
  partner_id uuid,
  transaction_date text not null,
  csv_clinic_name text not null,
  referring_vet text,
  client_name text,
  animal_name text,
  division text,
  amount numeric(12,2) default 0 not null,
  dedup_hash text not null,
  upload_id uuid,
  created_at timestamp with time zone default now() not null,
  row_index integer,
  invoice_line_id text
);

create table if not exists public.referral_sync_history (
  id uuid default gen_random_uuid() not null,
  filename text not null,
  upload_date timestamp with time zone default now() not null,
  date_range_start date,
  date_range_end date,
  total_rows_parsed integer default 0,
  total_rows_matched integer default 0,
  total_rows_skipped integer default 0,
  total_revenue_added numeric(12,2) default 0,
  uploaded_by uuid,
  sync_details jsonb default '{}'::jsonb,
  created_at timestamp with time zone default now() not null,
  content_hash text,
  report_type text,
  data_source text default 'csv_upload'::text
);
